### ISSUE TITLE
Builds timeout too quickly

### ISSUE THREAD

**Issue by recampbell** [buildhive/buildhive#10]
Builds timeout after 15 min. Perhaps we should raise this to something extra big (2 hrs) and then just manage by exception.

**Comment by kohsuke** [comment]
OK, let's do that.

**Comment by kohsuke** [comment]
Committed in `0a456e891e02cd15b723da4a97a9ae6c7cdcd39a`
This fix is now live.

**Comment by galderz** [comment]
Are you sure this is fixed? See: https://buildhive.cloudbees.com/job/infinispan/job/infinispan/82/consoleFull

It says build timed out after 120 minutes, but first timestamp is 2012-06-05 14:41:07,868, last timestamp: 2012-06-05 14:56:45,591

**Comment by galderz** [comment]
Thoughts?

**Comment by recampbell** [comment]
Well, if your build is stuck, it's probably not going to print out timestamps.

If you look at the build history page, Jenkin points out that #82 is the one build which took 2 hours, so it was killed.

https://buildhive.cloudbees.com/job/infinispan/job/infinispan/buildTimeTrend

Have you had continuing problems with builds being killed somewhere else?
