### ISSUE TITLE
Force a build when configuration changes

### ISSUE THREAD

**Issue by recampbell** [buildhive/buildhive#2]
If someone changes the configuration for their job, we should force a build so they don't have to do a fake commit to test the new configuration.

Alternatively, we could just let people force builds manually?

**Comment by kohsuke** [comment]
I've got a number of feedback from people for wanting to manually start a build. 

I'll give that permission to the users.

**Comment by kohsuke** [comment]
Deployed a new version that lets users start a new build manually
