### ISSUE TITLE
Support Gradle 1.0 final and Gradle Wrapper

### ISSUE THREAD

**Issue by pniederw** [buildhive/buildhive#23]
Gradle projects are currently built with Gradle 1.0-rc-1. Would be awesome if BuildHive used Gradle 1.0 final instead.

Is it possible to build with the Gradle Wrapper? This would be even better than using a fixed Gradle version. Maybe auto-detection could be changed to call the gradlew script if available.

According to Nicolas De Loof from CloudBees:

Gradle 1.0 and wrapper are supported on DEV@Cloud, this would make sense indeed to also make this update on buildhive. Please create a feature request on https://github.com/buildhive/buildhive/issues.

**Comment by pniederw** [comment]
Anyone?

**Comment by ndeloof** [comment]
buildhive now has a gradle template and will detect such a project based on existing build.gradle at project root

**Comment by ndeloof** [comment]
I'll investigate another template to add gradle wrapper support

**Comment by peterwalker** [comment]
Here is a project that you can test with.
https://buildhive.cloudbees.com/job/peterwalker/job/dependency/

**Comment by peterwalker** [comment]
By the way, the latest version of Gradle is 1.4. You might want to consider ONLY supporting builds that use the Gradle wrapper so that you don't have to refresh Gradle every 6 weeks.
