### ISSUE TITLE
Issues with sbt builds

### ISSUE THREAD

**Issue by jrudolph** [buildhive/buildhive#29]
This is the command line build-hive seems to use with Scala projects:

```
java -jar /tmp/sbt-launch.jar -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m clean test
```

This sends jvm options to the application instead of to the JVM. Aside from that it should use `-Dsbt.log.noformat=true` to avoid printing ANSI color codes (or otherwise use the Jenkins ANSIColor plugin).

So, in summary the command line should be this:

```
java -Dsbt.log.noformat=true -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -jar /tmp/sbt-launch.jar clean test
```

**Comment by ndeloof** [comment]
fixed

**Comment by jrudolph** [comment]
Thanks for fixing it.
