### ISSUE TITLE
Bundler + Rake Project Template is broken

### ISSUE THREAD

**Issue by klieber** [buildhive/buildhive#30]
I am attempting to build my project using the Bundler + Rake Project Template and I keep getting the following error:

```
mount: warning: /scratch/jenkins seems to be mounted read-write.
mount: warning: /scratch/jenkins/rubies seems to be mounted read-only.
mount: warning: /home/jenkins seems to be mounted read-only.
mount: warning: /scratch/jenkins/workspace/klieber seems to be mounted read-only.
+ curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/use-ruby
+ RUBY_VERSION=1.8.7-p357
+ source ./use-ruby
++ set -e
++ [[ -z 1.8.7-p357 ]]
++ echo 'This script is deprecated, please use https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby'
This script is deprecated, please use https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
++ mkdir -p /scratch/hudson/rubies
+++ uname -m
++ ARCH=i686
++ ruby_name=ruby-1.8.7-p357-i686
++ test -f /scratch/hudson/rubies/ruby-1.8.7-p357-i686.zip
++ wget -q -P /scratch/hudson/rubies https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/ruby-1.8.7-p357-i686.zip
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Here is a link to my build: https://buildhive.cloudbees.com/job/klieber/job/jasmine-maven-plugin/

It also appears this isn't limited to my project. It seems all recent builds using this template have failed with the same error:
https://buildhive.cloudbees.com/job/lunks/job/wargame/127/console
https://buildhive.cloudbees.com/job/rtyler/job/puppet-jenkins/50/console
https://buildhive.cloudbees.com/job/rkh/job/sinatra/16/console

**Comment by recampbell** [comment]
We did a deploy last night and broke this I'm afraid. We fixed this and it seems like your build is at least getting further now.

**Comment by klieber** [comment]
Thank you for your help!
