### ISSUE TITLE
Some Builds  fail with 'setup process failed (1): Success

### ISSUE THREAD

**Issue by recampbell** [buildhive/buildhive#4]
For example:

https://buildhive.cloudbees.com/job/C4J-Team/job/C4J/1/console

Maybe due to dash?  Seems consistent for this project.

**Comment by kohsuke** [comment]
The fix for allowing '-' is committed in f8889d5ca690eaf0b88277cfeba53bcf43b4a1d5.
Can you verify that this is ready to be pushed to production, and push it? That should solve the problem.

**Comment by recampbell** [comment]
This fix is live.
